declare module "dan200.computercraft.api.pocket.AbstractPocketUpgrade" {
import {$DataComponentPatch, $DataComponentPatch$$Type} from "net.minecraft.core.component.DataComponentPatch"
import {$IPocketAccess$$Type} from "dan200.computercraft.api.pocket.IPocketAccess"
import {$ResourceLocation$$Type} from "net.minecraft.resources.ResourceLocation"
import {$ItemStack, $ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Registry} from "net.minecraft.core.Registry"
import {$Level$$Type} from "net.minecraft.world.level.Level"
import {$ResourceKey} from "net.minecraft.resources.ResourceKey"
import {$IPocketUpgrade, $IPocketUpgrade$$Interface} from "dan200.computercraft.api.pocket.IPocketUpgrade"
import {$Component} from "net.minecraft.network.chat.Component"
import {$IPeripheral, $IPeripheral$$Type} from "dan200.computercraft.api.peripheral.IPeripheral"
import {$UpgradeType} from "dan200.computercraft.api.upgrades.UpgradeType"

export class $AbstractPocketUpgrade implements $IPocketUpgrade$$Interface {
public "getAdjective"(): $Component
public "getCraftingItem"(): $ItemStack
public "createPeripheral"(arg0: $IPocketAccess$$Type): $IPeripheral
public "onRightClick"(arg0: $Level$$Type, arg1: $IPocketAccess$$Type, arg2: $IPeripheral$$Type): boolean
public "update"(arg0: $IPocketAccess$$Type, arg1: $IPeripheral$$Type): void
public "getType"(): $UpgradeType<($IPocketUpgrade)>
public static "typeRegistry"(): $ResourceKey<($Registry<($UpgradeType<($IPocketUpgrade)>)>)>
public "getUpgradeData"(arg0: $ItemStack$$Type): $DataComponentPatch
public "getUpgradeItem"(arg0: $DataComponentPatch$$Type): $ItemStack
public "isItemSuitable"(arg0: $ItemStack$$Type): boolean
public static "getDefaultAdjective"(arg0: $ResourceLocation$$Type): StringJS
get "adjective"(): $Component
get "craftingItem"(): $ItemStack
get "type"(): $UpgradeType<($IPocketUpgrade)>
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $AbstractPocketUpgrade$$Type = ($AbstractPocketUpgrade);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $AbstractPocketUpgrade$$Original = $AbstractPocketUpgrade;}
declare module "dan200.computercraft.api.pocket.IPocketUpgrade" {
import {$DataComponentPatch, $DataComponentPatch$$Type} from "net.minecraft.core.component.DataComponentPatch"
import {$IPocketAccess$$Type} from "dan200.computercraft.api.pocket.IPocketAccess"
import {$ResourceLocation$$Type} from "net.minecraft.resources.ResourceLocation"
import {$ItemStack, $ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Registry} from "net.minecraft.core.Registry"
import {$UpgradeBase$$Interface} from "dan200.computercraft.api.upgrades.UpgradeBase"
import {$Level$$Type} from "net.minecraft.world.level.Level"
import {$ResourceKey} from "net.minecraft.resources.ResourceKey"
import {$Component} from "net.minecraft.network.chat.Component"
import {$IPeripheral, $IPeripheral$$Type} from "dan200.computercraft.api.peripheral.IPeripheral"
import {$UpgradeType} from "dan200.computercraft.api.upgrades.UpgradeType"

export interface $IPocketUpgrade$$Interface extends $UpgradeBase$$Interface {
get "type"(): $UpgradeType<($IPocketUpgrade)>
get "adjective"(): $Component
get "craftingItem"(): $ItemStack
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.ComputercraftPocketUpgrade
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.ComputercraftPocketUpgradeTag
}

export class $IPocketUpgrade implements $IPocketUpgrade$$Interface {
static readonly "REGISTRY": $ResourceKey<($Registry<($IPocketUpgrade)>)>

 "createPeripheral"(arg0: $IPocketAccess$$Type): $IPeripheral
 "onRightClick"(arg0: $Level$$Type, arg1: $IPocketAccess$$Type, arg2: $IPeripheral$$Type): boolean
 "update"(arg0: $IPocketAccess$$Type, arg1: $IPeripheral$$Type): void
 "getType"(): $UpgradeType<($IPocketUpgrade)>
static "typeRegistry"(): $ResourceKey<($Registry<($UpgradeType<($IPocketUpgrade)>)>)>
 "getUpgradeData"(arg0: $ItemStack$$Type): $DataComponentPatch
 "getAdjective"(): $Component
 "getUpgradeItem"(arg0: $DataComponentPatch$$Type): $ItemStack
 "getCraftingItem"(): $ItemStack
 "isItemSuitable"(arg0: $ItemStack$$Type): boolean
static "getDefaultAdjective"(arg0: $ResourceLocation$$Type): StringJS
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $IPocketUpgrade$$Type = (Special.ComputercraftPocketUpgrade);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $IPocketUpgrade$$Original = $IPocketUpgrade;}
declare module "dan200.computercraft.api.pocket.IPocketAccess" {
import {$UpgradeData, $UpgradeData$$Type} from "dan200.computercraft.api.upgrades.UpgradeData"
import {$DataComponentPatch, $DataComponentPatch$$Type} from "net.minecraft.core.component.DataComponentPatch"
import {$Vec3} from "net.minecraft.world.phys.Vec3"
import {$ServerLevel} from "net.minecraft.server.level.ServerLevel"
import {$IPocketUpgrade, $IPocketUpgrade$$Type} from "dan200.computercraft.api.pocket.IPocketUpgrade"
import {$Entity} from "net.minecraft.world.entity.Entity"

export interface $IPocketAccess$$Interface {
get "upgrade"(): $UpgradeData<($IPocketUpgrade)>
set "upgrade"(value: $UpgradeData$$Type<($IPocketUpgrade$$Type)>)
get "light"(): integer
get "upgradeData"(): $DataComponentPatch
set "colour"(value: integer)
get "colour"(): integer
set "upgradeData"(value: $DataComponentPatch$$Type)
get "position"(): $Vec3
get "level"(): $ServerLevel
get "entity"(): $Entity
set "light"(value: integer)
}

export class $IPocketAccess implements $IPocketAccess$$Interface {
 "getUpgrade"(): $UpgradeData<($IPocketUpgrade)>
 "setUpgrade"(arg0: $UpgradeData$$Type<($IPocketUpgrade$$Type)>): void
 "getLight"(): integer
 "getUpgradeData"(): $DataComponentPatch
 "setColour"(arg0: integer): void
 "getColour"(): integer
 "setUpgradeData"(arg0: $DataComponentPatch$$Type): void
 "invalidatePeripheral"(): void
 "getPosition"(): $Vec3
 "getLevel"(): $ServerLevel
 "getEntity"(): $Entity
 "setLight"(arg0: integer): void
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $IPocketAccess$$Type = ($IPocketAccess);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $IPocketAccess$$Original = $IPocketAccess;}
