declare module "moe.wolfgirl.probejs.generated.schema.oritech.CentrifugeFluid" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"
import {$FluidStack$$Type} from "net.neoforged.neoforge.fluids.FluidStack"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $CentrifugeFluid extends $KubeRecipe {
public "results"(results: $List$$Type<($ItemStack$$Type)>): this
public "fluidOutputs"(fluidOutputs: $List$$Type<($FluidStack$$Type)>): this
public "ingredients"(ingredients: $List$$Type<($Ingredient$$Type)>): this
public "fluidInput"(fluidInput: $FluidStack$$Type): this
public "time"(time: integer): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $CentrifugeFluid$$Type = ($CentrifugeFluid);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $CentrifugeFluid$$Original = $CentrifugeFluid;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.CreativeModeTab" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$CreativeModeTab as $CreativeModeTab$0} from "net.minecraft.world.item.CreativeModeTab"
import {$CreativeTabBuilder} from "dev.latvian.mods.kubejs.item.creativetab.CreativeTabBuilder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $CreativeModeTab extends $RegistryKubeEvent<($CreativeModeTab$0)> {
public "create"(name: StringJS): $CreativeTabBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $CreativeModeTab$$Type = ($CreativeModeTab);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $CreativeModeTab$$Original = $CreativeModeTab;}
declare module "moe.wolfgirl.probejs.generated.schema.oritech.ParticleCollision" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $ParticleCollision extends $KubeRecipe {
public "results"(results: $List$$Type<($ItemStack$$Type)>): this
public "ingredients"(ingredients: $List$$Type<($Ingredient$$Type)>): this
public "time"(time: integer): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ParticleCollision$$Type = ($ParticleCollision);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ParticleCollision$$Original = $ParticleCollision;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.SmithingTrim" {
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $SmithingTrim extends $KubeRecipe {
public "template"(template: $Ingredient$$Type): this
public "base"(base: $Ingredient$$Type): this
public "addition"(addition: $Ingredient$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SmithingTrim$$Type = ($SmithingTrim);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SmithingTrim$$Original = $SmithingTrim;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.CraftingShaped" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Map$$Type} from "java.util.Map"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"
import {$CraftingBookCategory$$Type} from "net.minecraft.world.item.crafting.CraftingBookCategory"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $CraftingShaped extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "pattern"(pattern: $List$$Type<(StringJS)>): this
public "key"(key: $Map$$Type<(character), ($Ingredient$$Type)>): this
public "kjsMirror"(kjsMirror: boolean): this
public "kjsShrink"(kjsShrink: boolean): this
public "category"(category: $CraftingBookCategory$$Type): this
public "showNotification"(showNotification: boolean): this
public "buildingCategory"(): this
public "equipmentCategory"(): this
public "redstoneCategory"(): this
public "noShrink"(): this
public "noNotification"(): this
public "noMirror"(): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $CraftingShaped$$Type = ($CraftingShaped);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $CraftingShaped$$Original = $CraftingShaped;}
declare module "moe.wolfgirl.probejs.generated.schema.oritech.Assembler" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Assembler extends $KubeRecipe {
public "results"(results: $List$$Type<($ItemStack$$Type)>): this
public "ingredients"(ingredients: $List$$Type<($Ingredient$$Type)>): this
public "time"(time: integer): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Assembler$$Type = ($Assembler);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Assembler$$Original = $Assembler;}
declare module "moe.wolfgirl.probejs.generated.schema.createoreexcavation.Extracting" {
import {$ExtractorRecipeJS} from "com.tom.createores.kubejs.ExtractorRecipeJS"
import {$FluidIngredient$$Type} from "com.tom.createores.util.FluidIngredient"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$FluidStack$$Type} from "net.neoforged.neoforge.fluids.FluidStack"
import {$TickDuration$$Type} from "dev.latvian.mods.kubejs.util.TickDuration"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Extracting extends $ExtractorRecipeJS {
public "output"(output: $FluidStack$$Type): this
public "ticks"(ticks: $TickDuration$$Type): this
public "veinId"(veinId: StringJS): this
public "drill"(drill: $Ingredient$$Type): this
public "priority"(priority: integer): this
public "fluid"(fluid: $FluidIngredient$$Type): this
public "stress"(stress: integer): this
public "drill"(arg0: $Ingredient$$Type): this
public "stress"(arg0: integer): this
public "priority"(arg0: integer): this
public "fluid"(arg0: $FluidIngredient$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Extracting$$Type = ($Extracting);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Extracting$$Original = $Extracting;}
declare module "moe.wolfgirl.probejs.generated.schema.createoreexcavation.Vein" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$RandomSpreadType$$Type} from "net.minecraft.world.level.levelgen.structure.placement.RandomSpreadType"
import {$RandomSpreadStructurePlacementJS$$Type} from "com.tom.createores.kubejs.RandomSpreadStructurePlacementJS"
import {$Component$$Type} from "net.minecraft.network.chat.Component"
import {$ThreeState$$Type} from "com.tom.createores.util.ThreeState"
import {$StructurePlacement$FrequencyReductionMethod$$Type} from "net.minecraft.world.level.levelgen.structure.placement.StructurePlacement$FrequencyReductionMethod"
import {$VeinRecipeJS} from "com.tom.createores.kubejs.VeinRecipeJS"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Vein extends $VeinRecipeJS {
public "name"(name: $Component$$Type): this
public "icon"(icon: $ItemStack$$Type): this
public "placement"(placement: $RandomSpreadStructurePlacementJS$$Type): this
public "priority"(priority: integer): this
public "finite"(finite: $ThreeState$$Type): this
public "amountMultiplierMin"(amountMultiplierMin: float): this
public "amountMultiplierMax"(amountMultiplierMax: float): this
public "biomeWhitelist"(biomeWhitelist: StringJS): this
public "biomeBlacklist"(biomeBlacklist: StringJS): this
public "alwaysInfinite"(): this
public "alwaysFinite"(): this
public "defaultFinite"(): this
public "veinSize"(arg0: float, arg1: float): this
public "biomeWhitelist"(arg0: StringJS): this
public "biomeBlacklist"(arg0: StringJS): this
public "placement"(arg0: integer, arg1: integer, arg2: integer): this
public "spread"(arg0: $RandomSpreadType$$Type): this
public "reduction"(arg0: $StructurePlacement$FrequencyReductionMethod$$Type): this
public "priority"(arg0: integer): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Vein$$Type = ($Vein);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Vein$$Original = $Vein;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.SoundEvent" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$SoundEventBuilder} from "dev.latvian.mods.kubejs.misc.SoundEventBuilder"
import {$SoundEvent as $SoundEvent$0} from "net.minecraft.sounds.SoundEvent"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $SoundEvent extends $RegistryKubeEvent<($SoundEvent$0)> {
public "create"(name: StringJS): $SoundEventBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SoundEvent$$Type = ($SoundEvent);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SoundEvent$$Original = $SoundEvent;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.Smoking" {
import {$CookingBookCategory$$Type} from "net.minecraft.world.item.crafting.CookingBookCategory"
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$TickDuration$$Type} from "dev.latvian.mods.kubejs.util.TickDuration"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Smoking extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "ingredient"(ingredient: $Ingredient$$Type): this
public "xp"(xp: float): this
public "time"(time: $TickDuration$$Type): this
public "category"(category: $CookingBookCategory$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Smoking$$Type = ($Smoking);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Smoking$$Original = $Smoking;}
declare module "moe.wolfgirl.probejs.generated.TagWrapperProbe" {
import {$TagWrapper} from "dev.latvian.mods.kubejs.server.tag.TagWrapper"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $TagWrapperProbe<T, I> extends $TagWrapper {
public "add"(...filters: (I)[]): this
public "remove"(...filters: (I)[]): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $TagWrapperProbe$$Type<T, I> = ($TagWrapperProbe<(T), (I)>);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $TagWrapperProbe$$Original<T, I> = $TagWrapperProbe<(T), (I)>;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.PointOfInterestType" {
import {$PoiType} from "net.minecraft.world.entity.ai.village.poi.PoiType"
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$PoiTypeBuilder} from "dev.latvian.mods.kubejs.misc.PoiTypeBuilder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $PointOfInterestType extends $RegistryKubeEvent<($PoiType)> {
public "create"(name: StringJS): $PoiTypeBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $PointOfInterestType$$Type = ($PointOfInterestType);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $PointOfInterestType$$Original = $PointOfInterestType;}
declare module "moe.wolfgirl.probejs.generated.schema.enderio.Tank" {
import {$TankKubeRecipe} from "com.almostreliable.kubeio.recipe.TankKubeRecipe"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Tank extends $TankKubeRecipe {
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Tank$$Type = ($Tank);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Tank$$Original = $Tank;}
declare module "moe.wolfgirl.probejs.generated.schema.oritech.AtomicForge" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $AtomicForge extends $KubeRecipe {
public "results"(results: $List$$Type<($ItemStack$$Type)>): this
public "ingredients"(ingredients: $List$$Type<($Ingredient$$Type)>): this
public "time"(time: integer): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $AtomicForge$$Type = ($AtomicForge);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $AtomicForge$$Original = $AtomicForge;}
declare module "moe.wolfgirl.probejs.generated.schema.oritech.Foundry" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Foundry extends $KubeRecipe {
public "results"(results: $List$$Type<($ItemStack$$Type)>): this
public "ingredients"(ingredients: $List$$Type<($Ingredient$$Type)>): this
public "time"(time: integer): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Foundry$$Type = ($Foundry);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Foundry$$Original = $Foundry;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.Stonecutting" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Stonecutting extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "ingredient"(ingredient: $Ingredient$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Stonecutting$$Type = ($Stonecutting);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Stonecutting$$Original = $Stonecutting;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.VillagerType" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$VillagerTypeBuilder} from "dev.latvian.mods.kubejs.misc.VillagerTypeBuilder"
import {$VillagerType as $VillagerType$0} from "net.minecraft.world.entity.npc.VillagerType"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $VillagerType extends $RegistryKubeEvent<($VillagerType$0)> {
public "create"(name: StringJS): $VillagerTypeBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $VillagerType$$Type = ($VillagerType);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $VillagerType$$Original = $VillagerType;}
declare module "moe.wolfgirl.probejs.generated.schema.enderio.SagMilling" {
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$SagMillingRecipe$BonusType$$Type} from "com.enderio.enderio.content.machines.sag_mill.SagMillingRecipe$BonusType"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $SagMilling extends $KubeRecipe {
public "energy"(energy: integer): this
public "bonus"(bonus: $SagMillingRecipe$BonusType$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SagMilling$$Type = ($SagMilling);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SagMilling$$Original = $SagMilling;}
declare module "moe.wolfgirl.probejs.generated.schema.enderio.AlloySmelting" {
import {$AlloySmelterKubeRecipe} from "com.almostreliable.kubeio.recipe.AlloySmelterKubeRecipe"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $AlloySmelting extends $AlloySmelterKubeRecipe {
public "energy"(energy: integer): this
public "experience"(experience: float): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $AlloySmelting$$Type = ($AlloySmelting);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $AlloySmelting$$Original = $AlloySmelting;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.Block" {
import {$CarpetBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.CarpetBlockBuilder"
import {$SlabBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.SlabBlockBuilder"
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$DoorBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.DoorBlockBuilder"
import {$StairBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.StairBlockBuilder"
import {$Block as $Block$0} from "net.minecraft.world.level.block.Block"
import {$PressurePlateBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.PressurePlateBlockBuilder"
import {$BasicKubeBlock$Builder} from "dev.latvian.mods.kubejs.block.custom.BasicKubeBlock$Builder"
import {$CropBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.CropBlockBuilder"
import {$ButtonBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.ButtonBlockBuilder"
import {$FenceBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.FenceBlockBuilder"
import {$TrapdoorBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.TrapdoorBlockBuilder"
import {$WallBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.WallBlockBuilder"
import {$CardinalBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.CardinalBlockBuilder"
import {$FenceGateBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.FenceGateBlockBuilder"
import {$FallingBlockBuilder} from "dev.latvian.mods.kubejs.block.custom.FallingBlockBuilder"
import {$DetectorBlock$Builder} from "dev.latvian.mods.kubejs.block.DetectorBlock$Builder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Block extends $RegistryKubeEvent<($Block$0)> {
public "create"(name: StringJS): $BasicKubeBlock$Builder
public "create"(name: StringJS, type: "kubejs:detector"): $DetectorBlock$Builder
public "create"(name: StringJS, type: "kubejs:slab"): $SlabBlockBuilder
public "create"(name: StringJS, type: "kubejs:stairs"): $StairBlockBuilder
public "create"(name: StringJS, type: "kubejs:fence"): $FenceBlockBuilder
public "create"(name: StringJS, type: "kubejs:wall"): $WallBlockBuilder
public "create"(name: StringJS, type: "kubejs:fence_gate"): $FenceGateBlockBuilder
public "create"(name: StringJS, type: "kubejs:pressure_plate"): $PressurePlateBlockBuilder
public "create"(name: StringJS, type: "kubejs:button"): $ButtonBlockBuilder
public "create"(name: StringJS, type: "kubejs:falling"): $FallingBlockBuilder
public "create"(name: StringJS, type: "kubejs:crop"): $CropBlockBuilder
public "create"(name: StringJS, type: "kubejs:cardinal"): $CardinalBlockBuilder
public "create"(name: StringJS, type: "kubejs:carpet"): $CarpetBlockBuilder
public "create"(name: StringJS, type: "kubejs:door"): $DoorBlockBuilder
public "create"(name: StringJS, type: "kubejs:trapdoor"): $TrapdoorBlockBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Block$$Type = ($Block);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Block$$Original = $Block;}
declare module "moe.wolfgirl.probejs.generated.schema.oritech.Grinder" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Grinder extends $KubeRecipe {
public "results"(results: $List$$Type<($ItemStack$$Type)>): this
public "ingredients"(ingredients: $List$$Type<($Ingredient$$Type)>): this
public "time"(time: integer): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Grinder$$Type = ($Grinder);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Grinder$$Original = $Grinder;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.Smelting" {
import {$CookingBookCategory$$Type} from "net.minecraft.world.item.crafting.CookingBookCategory"
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$TickDuration$$Type} from "dev.latvian.mods.kubejs.util.TickDuration"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Smelting extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "ingredient"(ingredient: $Ingredient$$Type): this
public "xp"(xp: float): this
public "time"(time: $TickDuration$$Type): this
public "category"(category: $CookingBookCategory$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Smelting$$Type = ($Smelting);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Smelting$$Original = $Smelting;}
declare module "moe.wolfgirl.probejs.generated.schema.kubejs.Shapeless" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"
import {$CraftingBookCategory$$Type} from "net.minecraft.world.item.crafting.CraftingBookCategory"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Shapeless extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "ingredients"(ingredients: $List$$Type<($Ingredient$$Type)>): this
public "category"(category: $CraftingBookCategory$$Type): this
public "buildingCategory"(): this
public "equipmentCategory"(): this
public "redstoneCategory"(): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Shapeless$$Type = ($Shapeless);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Shapeless$$Original = $Shapeless;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.Item" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$ShearsItemBuilder} from "dev.latvian.mods.kubejs.item.custom.ShearsItemBuilder"
import {$DiggerItemBuilder$Axe} from "dev.latvian.mods.kubejs.item.custom.DiggerItemBuilder$Axe"
import {$DiggerItemBuilder$Shovel} from "dev.latvian.mods.kubejs.item.custom.DiggerItemBuilder$Shovel"
import {$ArmorItemBuilder$Boots} from "dev.latvian.mods.kubejs.item.custom.ArmorItemBuilder$Boots"
import {$SmithingTemplateItemBuilder} from "dev.latvian.mods.kubejs.item.custom.SmithingTemplateItemBuilder"
import {$ArmorItemBuilder$Helmet} from "dev.latvian.mods.kubejs.item.custom.ArmorItemBuilder$Helmet"
import {$ArmorItemBuilder$AnimalArmor} from "dev.latvian.mods.kubejs.item.custom.ArmorItemBuilder$AnimalArmor"
import {$ArmorItemBuilder$Chestplate} from "dev.latvian.mods.kubejs.item.custom.ArmorItemBuilder$Chestplate"
import {$SwordItemBuilder} from "dev.latvian.mods.kubejs.item.custom.SwordItemBuilder"
import {$DiggerItemBuilder$Hoe} from "dev.latvian.mods.kubejs.item.custom.DiggerItemBuilder$Hoe"
import {$DiggerItemBuilder$Pickaxe} from "dev.latvian.mods.kubejs.item.custom.DiggerItemBuilder$Pickaxe"
import {$ItemBuilder} from "dev.latvian.mods.kubejs.item.ItemBuilder"
import {$Item as $Item$0} from "net.minecraft.world.item.Item"
import {$ArmorItemBuilder$Leggings} from "dev.latvian.mods.kubejs.item.custom.ArmorItemBuilder$Leggings"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Item extends $RegistryKubeEvent<($Item$0)> {
public "create"(name: StringJS): $ItemBuilder
public "create"(name: StringJS, type: "kubejs:sword"): $SwordItemBuilder
public "create"(name: StringJS, type: "kubejs:pickaxe"): $DiggerItemBuilder$Pickaxe
public "create"(name: StringJS, type: "kubejs:axe"): $DiggerItemBuilder$Axe
public "create"(name: StringJS, type: "kubejs:shovel"): $DiggerItemBuilder$Shovel
public "create"(name: StringJS, type: "kubejs:hoe"): $DiggerItemBuilder$Hoe
public "create"(name: StringJS, type: "kubejs:shears"): $ShearsItemBuilder
public "create"(name: StringJS, type: "kubejs:helmet"): $ArmorItemBuilder$Helmet
public "create"(name: StringJS, type: "kubejs:chestplate"): $ArmorItemBuilder$Chestplate
public "create"(name: StringJS, type: "kubejs:leggings"): $ArmorItemBuilder$Leggings
public "create"(name: StringJS, type: "kubejs:boots"): $ArmorItemBuilder$Boots
public "create"(name: StringJS, type: "kubejs:animal_armor"): $ArmorItemBuilder$AnimalArmor
public "create"(name: StringJS, type: "kubejs:smithing_template"): $SmithingTemplateItemBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Item$$Type = ($Item);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Item$$Original = $Item;}
declare module "moe.wolfgirl.probejs.generated.schema.oritech.Centrifuge" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Centrifuge extends $KubeRecipe {
public "results"(results: $List$$Type<($ItemStack$$Type)>): this
public "ingredients"(ingredients: $List$$Type<($Ingredient$$Type)>): this
public "time"(time: integer): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Centrifuge$$Type = ($Centrifuge);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Centrifuge$$Original = $Centrifuge;}
declare module "moe.wolfgirl.probejs.generated.TagEventProbe" {
import {$TagWrapperProbe} from "moe.wolfgirl.probejs.generated.TagWrapperProbe"
import {$TagKubeEvent} from "dev.latvian.mods.kubejs.server.tag.TagKubeEvent"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $TagEventProbe<T, I> extends $TagKubeEvent {
public "add"(tag: T, ...filters: (I)[]): $TagWrapperProbe<(T), (I)>
public "remove"(tag: T, ...filters: (I)[]): $TagWrapperProbe<(T), (I)>
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $TagEventProbe$$Type<T, I> = ($TagEventProbe<(T), (I)>);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $TagEventProbe$$Original<T, I> = $TagEventProbe<(T), (I)>;}
declare module "moe.wolfgirl.probejs.generated.schema.oritech.Refinery" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"
import {$FluidStack$$Type} from "net.neoforged.neoforge.fluids.FluidStack"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Refinery extends $KubeRecipe {
public "results"(results: $List$$Type<($ItemStack$$Type)>): this
public "fluidOutputs"(fluidOutputs: $List$$Type<($FluidStack$$Type)>): this
public "ingredients"(ingredients: $List$$Type<($Ingredient$$Type)>): this
public "fluidInput"(fluidInput: $FluidStack$$Type): this
public "time"(time: integer): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Refinery$$Type = ($Refinery);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Refinery$$Original = $Refinery;}
declare module "moe.wolfgirl.probejs.generated.schema.createoreexcavation.Drilling" {
import {$FluidIngredient$$Type} from "com.tom.createores.util.FluidIngredient"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$List$$Type} from "java.util.List"
import {$ProcessingOutput$$Type} from "com.simibubi.create.content.processing.recipe.ProcessingOutput"
import {$DrillingRecipeJS} from "com.tom.createores.kubejs.DrillingRecipeJS"
import {$TickDuration$$Type} from "dev.latvian.mods.kubejs.util.TickDuration"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Drilling extends $DrillingRecipeJS {
public "output"(output: ($List$$Type<($ProcessingOutput$$Type)>) | ($ProcessingOutput$$Type)): this
public "ticks"(ticks: $TickDuration$$Type): this
public "veinId"(veinId: StringJS): this
public "drill"(drill: $Ingredient$$Type): this
public "priority"(priority: integer): this
public "fluid"(fluid: $FluidIngredient$$Type): this
public "stress"(stress: integer): this
public "drill"(arg0: $Ingredient$$Type): this
public "stress"(arg0: integer): this
public "priority"(arg0: integer): this
public "fluid"(arg0: $FluidIngredient$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Drilling$$Type = ($Drilling);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Drilling$$Original = $Drilling;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.Blasting" {
import {$CookingBookCategory$$Type} from "net.minecraft.world.item.crafting.CookingBookCategory"
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$TickDuration$$Type} from "dev.latvian.mods.kubejs.util.TickDuration"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Blasting extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "ingredient"(ingredient: $Ingredient$$Type): this
public "xp"(xp: float): this
public "time"(time: $TickDuration$$Type): this
public "category"(category: $CookingBookCategory$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Blasting$$Type = ($Blasting);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Blasting$$Original = $Blasting;}
declare module "moe.wolfgirl.probejs.generated.schema.enderio.VatFermenting" {
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $VatFermenting extends $KubeRecipe {
public "ticks"(ticks: integer): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $VatFermenting$$Type = ($VatFermenting);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $VatFermenting$$Original = $VatFermenting;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.CraftingShapeless" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"
import {$CraftingBookCategory$$Type} from "net.minecraft.world.item.crafting.CraftingBookCategory"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $CraftingShapeless extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "ingredients"(ingredients: $List$$Type<($Ingredient$$Type)>): this
public "category"(category: $CraftingBookCategory$$Type): this
public "buildingCategory"(): this
public "equipmentCategory"(): this
public "redstoneCategory"(): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $CraftingShapeless$$Type = ($CraftingShapeless);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $CraftingShapeless$$Original = $CraftingShapeless;}
declare module "moe.wolfgirl.probejs.generated.schema.enderio.Slicing" {
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Slicing extends $KubeRecipe {
public "energy"(energy: integer): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Slicing$$Type = ($Slicing);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Slicing$$Original = $Slicing;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.ArmorMaterial" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$ArmorMaterial as $ArmorMaterial$0} from "net.minecraft.world.item.ArmorMaterial"
import {$ArmorMaterialBuilder} from "dev.latvian.mods.kubejs.item.ArmorMaterialBuilder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $ArmorMaterial extends $RegistryKubeEvent<($ArmorMaterial$0)> {
public "create"(name: StringJS): $ArmorMaterialBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ArmorMaterial$$Type = ($ArmorMaterial);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ArmorMaterial$$Original = $ArmorMaterial;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.CustomStat" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$CustomStatBuilder} from "dev.latvian.mods.kubejs.misc.CustomStatBuilder"
import {$ResourceLocation} from "net.minecraft.resources.ResourceLocation"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $CustomStat extends $RegistryKubeEvent<($ResourceLocation)> {
public "create"(name: StringJS): $CustomStatBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $CustomStat$$Type = ($CustomStat);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $CustomStat$$Original = $CustomStat;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.CampfireCooking" {
import {$CookingBookCategory$$Type} from "net.minecraft.world.item.crafting.CookingBookCategory"
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$TickDuration$$Type} from "dev.latvian.mods.kubejs.util.TickDuration"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $CampfireCooking extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "ingredient"(ingredient: $Ingredient$$Type): this
public "xp"(xp: float): this
public "time"(time: $TickDuration$$Type): this
public "category"(category: $CookingBookCategory$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $CampfireCooking$$Type = ($CampfireCooking);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $CampfireCooking$$Original = $CampfireCooking;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.Potion" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$Potion as $Potion$0} from "net.minecraft.world.item.alchemy.Potion"
import {$PotionBuilder} from "dev.latvian.mods.kubejs.misc.PotionBuilder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Potion extends $RegistryKubeEvent<($Potion$0)> {
public "create"(name: StringJS): $PotionBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Potion$$Type = ($Potion);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Potion$$Original = $Potion;}
declare module "moe.wolfgirl.probejs.generated.schema.extendedcrafting.ShapedTable" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Map$$Type} from "java.util.Map"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"
import {$CraftingBookCategory$$Type} from "net.minecraft.world.item.crafting.CraftingBookCategory"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $ShapedTable extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "pattern"(pattern: $List$$Type<(StringJS)>): this
public "key"(key: $Map$$Type<(character), ($Ingredient$$Type)>): this
public "kjsMirror"(kjsMirror: boolean): this
public "kjsShrink"(kjsShrink: boolean): this
public "category"(category: $CraftingBookCategory$$Type): this
public "showNotification"(showNotification: boolean): this
public "buildingCategory"(): this
public "equipmentCategory"(): this
public "redstoneCategory"(): this
public "noShrink"(): this
public "noNotification"(): this
public "noMirror"(): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ShapedTable$$Type = ($ShapedTable);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ShapedTable$$Original = $ShapedTable;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.Fluid" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$ThickFluidBuilder} from "dev.latvian.mods.kubejs.fluid.ThickFluidBuilder"
import {$ThinFluidBuilder} from "dev.latvian.mods.kubejs.fluid.ThinFluidBuilder"
import {$Fluid as $Fluid$0} from "net.minecraft.world.level.material.Fluid"
import {$FluidBuilder} from "dev.latvian.mods.kubejs.fluid.FluidBuilder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Fluid extends $RegistryKubeEvent<($Fluid$0)> {
public "create"(name: StringJS): $FluidBuilder
public "create"(name: StringJS, type: "kubejs:thin"): $ThinFluidBuilder
public "create"(name: StringJS, type: "kubejs:thick"): $ThickFluidBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Fluid$$Type = ($Fluid);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Fluid$$Original = $Fluid;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.VillagerProfession" {
import {$VillagerProfessionBuilder} from "dev.latvian.mods.kubejs.misc.VillagerProfessionBuilder"
import {$VillagerProfession as $VillagerProfession$0} from "net.minecraft.world.entity.npc.VillagerProfession"
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $VillagerProfession extends $RegistryKubeEvent<($VillagerProfession$0)> {
public "create"(name: StringJS): $VillagerProfessionBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $VillagerProfession$$Type = ($VillagerProfession);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $VillagerProfession$$Original = $VillagerProfession;}
declare module "moe.wolfgirl.probejs.generated.DocumentedRecipes" {
import {$SoulBinding} from "moe.wolfgirl.probejs.generated.schema.enderio.SoulBinding"
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$ShapelessTable} from "moe.wolfgirl.probejs.generated.schema.extendedcrafting.ShapelessTable"
import {$Shaped} from "moe.wolfgirl.probejs.generated.schema.kubejs.Shaped"
import {$Enchanting} from "moe.wolfgirl.probejs.generated.schema.enderio.Enchanting"
import {$RandomSpreadStructurePlacementJS$$Type} from "com.tom.createores.kubejs.RandomSpreadStructurePlacementJS"
import {$FluidStack$$Type} from "net.neoforged.neoforge.fluids.FluidStack"
import {$FluidIngredient$$Type} from "com.tom.createores.util.FluidIngredient"
import {$FireCrafting} from "moe.wolfgirl.probejs.generated.schema.enderio.FireCrafting"
import {$CentrifugeFluid} from "moe.wolfgirl.probejs.generated.schema.oritech.CentrifugeFluid"
import {$AtomicForge} from "moe.wolfgirl.probejs.generated.schema.oritech.AtomicForge"
import {$Extracting} from "moe.wolfgirl.probejs.generated.schema.createoreexcavation.Extracting"
import {$TickDuration$$Type} from "dev.latvian.mods.kubejs.util.TickDuration"
import {$SagMillingRecipe$BonusType$$Type} from "com.enderio.enderio.content.machines.sag_mill.SagMillingRecipe$BonusType"
import {$Slicing} from "moe.wolfgirl.probejs.generated.schema.enderio.Slicing"
import {$Laser} from "moe.wolfgirl.probejs.generated.schema.oritech.Laser"
import {$Pulverizer} from "moe.wolfgirl.probejs.generated.schema.oritech.Pulverizer"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$Refinery} from "moe.wolfgirl.probejs.generated.schema.oritech.Refinery"
import {$Smelting} from "moe.wolfgirl.probejs.generated.schema.minecraft.Smelting"
import {$Blasting} from "moe.wolfgirl.probejs.generated.schema.minecraft.Blasting"
import {$CampfireCooking} from "moe.wolfgirl.probejs.generated.schema.minecraft.CampfireCooking"
import {$Shapeless} from "moe.wolfgirl.probejs.generated.schema.kubejs.Shapeless"
import {$Smoking} from "moe.wolfgirl.probejs.generated.schema.minecraft.Smoking"
import {$Painting} from "moe.wolfgirl.probejs.generated.schema.enderio.Painting"
import {$ParticleCollision} from "moe.wolfgirl.probejs.generated.schema.oritech.ParticleCollision"
import {$Grinder} from "moe.wolfgirl.probejs.generated.schema.oritech.Grinder"
import {$CraftingShapeless} from "moe.wolfgirl.probejs.generated.schema.minecraft.CraftingShapeless"
import {$List$$Type} from "java.util.List"
import {$Stonecutting} from "moe.wolfgirl.probejs.generated.schema.minecraft.Stonecutting"
import {$ProcessingOutput$$Type} from "com.simibubi.create.content.processing.recipe.ProcessingOutput"
import {$Component$$Type} from "net.minecraft.network.chat.Component"
import {$Cooler} from "moe.wolfgirl.probejs.generated.schema.oritech.Cooler"
import {$Centrifuge} from "moe.wolfgirl.probejs.generated.schema.oritech.Centrifuge"
import {$Drilling} from "moe.wolfgirl.probejs.generated.schema.createoreexcavation.Drilling"
import {$Foundry} from "moe.wolfgirl.probejs.generated.schema.oritech.Foundry"
import {$SmithingTransform} from "moe.wolfgirl.probejs.generated.schema.minecraft.SmithingTransform"
import {$CraftingShaped} from "moe.wolfgirl.probejs.generated.schema.minecraft.CraftingShaped"
import {$Map$$Type} from "java.util.Map"
import {$VatFermenting} from "moe.wolfgirl.probejs.generated.schema.enderio.VatFermenting"
import {$ShapedTable} from "moe.wolfgirl.probejs.generated.schema.extendedcrafting.ShapedTable"
import {$ThreeState$$Type} from "com.tom.createores.util.ThreeState"
import {$Assembler} from "moe.wolfgirl.probejs.generated.schema.oritech.Assembler"
import {$AlloySmelting} from "moe.wolfgirl.probejs.generated.schema.enderio.AlloySmelting"
import {$SmithingTrim} from "moe.wolfgirl.probejs.generated.schema.minecraft.SmithingTrim"
import {$Tank} from "moe.wolfgirl.probejs.generated.schema.enderio.Tank"
import {$Vein} from "moe.wolfgirl.probejs.generated.schema.createoreexcavation.Vein"
import {$SagMilling} from "moe.wolfgirl.probejs.generated.schema.enderio.SagMilling"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $DocumentedRecipes {
 "industrialforegoing": {}
 "minecraft": {"blasting": (result: $ItemStack$$Type, ingredient: $Ingredient$$Type, xp?: float, time?: $TickDuration$$Type) => $Blasting, "crafting_shapeless": (result: $ItemStack$$Type, ingredients: $List$$Type<($Ingredient$$Type)>) => $CraftingShapeless, "crafting_shaped": (result: $ItemStack$$Type, pattern: $List$$Type<(StringJS)>, key: $Map$$Type<(character), ($Ingredient$$Type)>) => $CraftingShaped, "stonecutting": (result: $ItemStack$$Type, ingredient: $Ingredient$$Type) => $Stonecutting, "smelting": (result: $ItemStack$$Type, ingredient: $Ingredient$$Type, xp?: float, time?: $TickDuration$$Type) => $Smelting, "smoking": (result: $ItemStack$$Type, ingredient: $Ingredient$$Type, xp?: float, time?: $TickDuration$$Type) => $Smoking, "campfire_cooking": (result: $ItemStack$$Type, ingredient: $Ingredient$$Type, xp?: float, time?: $TickDuration$$Type) => $CampfireCooking, "smithing_trim": (template: $Ingredient$$Type, base: $Ingredient$$Type, addition: $Ingredient$$Type) => $SmithingTrim, "smithing_transform": (result: $ItemStack$$Type, template: $Ingredient$$Type, base: $Ingredient$$Type, addition: $Ingredient$$Type) => $SmithingTransform}
 "rftoolsutility": {}
 "simplyswords": {}
 "kubejs": {"shapeless": (result: $ItemStack$$Type, ingredients: $List$$Type<($Ingredient$$Type)>) => $Shapeless, "shaped": (result: $ItemStack$$Type, pattern: $List$$Type<(StringJS)>, key: $Map$$Type<(character), ($Ingredient$$Type)>) => $Shaped}
 "apothic_spawners": {}
 "cucumber": {}
 "immersiveengineering": {}
 "createoreexcavation": {"vein": (name: $Component$$Type, icon: $ItemStack$$Type, placement: $RandomSpreadStructurePlacementJS$$Type, priority?: integer, finite?: $ThreeState$$Type, amountMultiplierMin?: float, amountMultiplierMax?: float, biomeWhitelist?: StringJS, biomeBlacklist?: StringJS) => $Vein, "extracting": (output: $FluidStack$$Type, ticks: $TickDuration$$Type, veinId: StringJS, drill?: $Ingredient$$Type, priority?: integer, fluid?: $FluidIngredient$$Type, stress?: integer) => $Extracting, "drilling": (output: ($List$$Type<($ProcessingOutput$$Type)>) | ($ProcessingOutput$$Type), ticks: $TickDuration$$Type, veinId: StringJS, drill?: $Ingredient$$Type, priority?: integer, fluid?: $FluidIngredient$$Type, stress?: integer) => $Drilling}
 "justhammers": {}
 "jei": {}
 "ae2": {}
 "supermartijn642corelib": {}
 "extendedcrafting": {"shaped_table": (result: $ItemStack$$Type, pattern: $List$$Type<(StringJS)>, key: $Map$$Type<(character), ($Ingredient$$Type)>) => $ShapedTable, "shapeless_table": (result: $ItemStack$$Type, ingredients: $List$$Type<($Ingredient$$Type)>) => $ShapelessTable}
 "enderio": {"fire_crafting": () => $FireCrafting, "painting": () => $Painting, "tank": () => $Tank, "sag_milling": (energy?: integer, bonus?: $SagMillingRecipe$BonusType$$Type) => $SagMilling, "vat_fermenting": (ticks?: integer) => $VatFermenting, "soul_binding": (energy?: integer, experience?: float) => $SoulBinding, "enchanting": (costMultiplier?: integer) => $Enchanting, "alloy_smelting": (energy?: integer, experience?: float) => $AlloySmelting, "slicing": (energy?: integer) => $Slicing}
 "sophisticatedcore": {}
 "create": {}
 "dankstorage": {}
 "simplehats": {}
 "almostunified": {}
 "framedblocks": {}
 "irons_spellbooks": {}
 "powah": {}
 "pneumaticcraft": {}
 "oritech": {"pulverizer": (results: $List$$Type<($ItemStack$$Type)>, ingredients: $List$$Type<($Ingredient$$Type)>, time?: integer) => $Pulverizer, "refinery": (results: $List$$Type<($ItemStack$$Type)>, fluidOutputs: $List$$Type<($FluidStack$$Type)>, ingredients: $List$$Type<($Ingredient$$Type)>, fluidInput: $FluidStack$$Type, time?: integer) => $Refinery, "cooler": (results: $List$$Type<($ItemStack$$Type)>, fluidOutputs: $List$$Type<($FluidStack$$Type)>, ingredients: $List$$Type<($Ingredient$$Type)>, fluidInput: $FluidStack$$Type, time?: integer) => $Cooler, "foundry": (results: $List$$Type<($ItemStack$$Type)>, ingredients: $List$$Type<($Ingredient$$Type)>, time?: integer) => $Foundry, "laser": (results: $List$$Type<($ItemStack$$Type)>, ingredients: $List$$Type<($Ingredient$$Type)>, time?: integer) => $Laser, "atomic_forge": (results: $List$$Type<($ItemStack$$Type)>, ingredients: $List$$Type<($Ingredient$$Type)>, time?: integer) => $AtomicForge, "grinder": (results: $List$$Type<($ItemStack$$Type)>, ingredients: $List$$Type<($Ingredient$$Type)>, time?: integer) => $Grinder, "centrifuge": (results: $List$$Type<($ItemStack$$Type)>, ingredients: $List$$Type<($Ingredient$$Type)>, time?: integer) => $Centrifuge, "particle_collision": (results: $List$$Type<($ItemStack$$Type)>, ingredients: $List$$Type<($Ingredient$$Type)>, time?: integer) => $ParticleCollision, "assembler": (results: $List$$Type<($ItemStack$$Type)>, ingredients: $List$$Type<($Ingredient$$Type)>, time?: integer) => $Assembler, "centrifuge_fluid": (results: $List$$Type<($ItemStack$$Type)>, fluidOutputs: $List$$Type<($FluidStack$$Type)>, ingredients: $List$$Type<($Ingredient$$Type)>, fluidInput: $FluidStack$$Type, time?: integer) => $CentrifugeFluid}
 "rftoolsdim": {}
 "sophisticatedbackpacks": {}
 "apotheosis": {}
 "mcjtylib": {}
 "computercraft": {}
 "create_new_age": {}
 "apothic_enchanting": {}
 "functionalstorage": {}
 "camerapture": {}
 "supplementaries": {}
 "reconstructedwands": {}
 "createaddition": {}
 "chipped": {}

}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $DocumentedRecipes$$Type = ($DocumentedRecipes);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $DocumentedRecipes$$Original = $DocumentedRecipes;}
declare module "moe.wolfgirl.probejs.generated.schema.oritech.Cooler" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"
import {$FluidStack$$Type} from "net.neoforged.neoforge.fluids.FluidStack"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Cooler extends $KubeRecipe {
public "results"(results: $List$$Type<($ItemStack$$Type)>): this
public "fluidOutputs"(fluidOutputs: $List$$Type<($FluidStack$$Type)>): this
public "ingredients"(ingredients: $List$$Type<($Ingredient$$Type)>): this
public "fluidInput"(fluidInput: $FluidStack$$Type): this
public "time"(time: integer): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Cooler$$Type = ($Cooler);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Cooler$$Original = $Cooler;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.MobEffect" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$MobEffectBuilder} from "dev.latvian.mods.kubejs.misc.MobEffectBuilder"
import {$MobEffect as $MobEffect$0} from "net.minecraft.world.effect.MobEffect"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $MobEffect extends $RegistryKubeEvent<($MobEffect$0)> {
public "create"(name: StringJS): $MobEffectBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $MobEffect$$Type = ($MobEffect);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $MobEffect$$Original = $MobEffect;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.Attribute" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$Attribute as $Attribute$0} from "net.minecraft.world.entity.ai.attributes.Attribute"
import {$AttributeBuilder} from "dev.latvian.mods.kubejs.entity.AttributeBuilder"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Attribute extends $RegistryKubeEvent<($Attribute$0)> {
public "create"(name: StringJS): $AttributeBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Attribute$$Type = ($Attribute);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Attribute$$Original = $Attribute;}
declare module "moe.wolfgirl.probejs.generated.schema.enderio.SoulBinding" {
import {$MobCategory$$Type} from "net.minecraft.world.entity.MobCategory"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$TagKey$$Type} from "net.minecraft.tags.TagKey"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $SoulBinding extends $KubeRecipe {
public "energy"(energy: integer): this
public "experience"(experience: float): this
public "entityType"(entityType: $TagKey$$Type): this
public "mobCategory"(mobCategory: $MobCategory$$Type): this
public "soulData"(soulData: StringJS): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SoulBinding$$Type = ($SoulBinding);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SoulBinding$$Original = $SoulBinding;}
declare module "moe.wolfgirl.probejs.generated.schema.enderio.Painting" {
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Painting extends $KubeRecipe {
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Painting$$Type = ($Painting);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Painting$$Original = $Painting;}
declare module "moe.wolfgirl.probejs.generated.registry.neoforge.FluidType" {
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$FluidTypeBuilder} from "dev.latvian.mods.kubejs.fluid.FluidTypeBuilder"
import {$FluidType as $FluidType$0} from "net.neoforged.neoforge.fluids.FluidType"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $FluidType extends $RegistryKubeEvent<($FluidType$0)> {
public "create"(name: StringJS): $FluidTypeBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $FluidType$$Type = ($FluidType);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $FluidType$$Original = $FluidType;}
declare module "moe.wolfgirl.probejs.generated.schema.enderio.FireCrafting" {
import {$LevelStem$$Type} from "net.minecraft.world.level.dimension.LevelStem"
import {$List$$Type} from "java.util.List"
import {$Block$$Type} from "net.minecraft.world.level.block.Block"
import {$ResourceKey$$Type} from "net.minecraft.resources.ResourceKey"
import {$FireCraftingKubeRecipe} from "com.almostreliable.kubeio.recipe.FireCraftingKubeRecipe"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $FireCrafting extends $FireCraftingKubeRecipe {
public "blockAfterBurning"(blockAfterBurning: $Block$$Type): this
public "dimensions"(dimensions: $List$$Type<($ResourceKey$$Type<($LevelStem$$Type)>)>): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $FireCrafting$$Type = ($FireCrafting);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $FireCrafting$$Original = $FireCrafting;}
declare module "moe.wolfgirl.probejs.generated.schema.kubejs.Shaped" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Map$$Type} from "java.util.Map"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"
import {$CraftingBookCategory$$Type} from "net.minecraft.world.item.crafting.CraftingBookCategory"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Shaped extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "pattern"(pattern: $List$$Type<(StringJS)>): this
public "key"(key: $Map$$Type<(character), ($Ingredient$$Type)>): this
public "kjsMirror"(kjsMirror: boolean): this
public "kjsShrink"(kjsShrink: boolean): this
public "category"(category: $CraftingBookCategory$$Type): this
public "showNotification"(showNotification: boolean): this
public "buildingCategory"(): this
public "equipmentCategory"(): this
public "redstoneCategory"(): this
public "noShrink"(): this
public "noNotification"(): this
public "noMirror"(): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Shaped$$Type = ($Shaped);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Shaped$$Original = $Shaped;}
declare module "moe.wolfgirl.probejs.generated.schema.enderio.Enchanting" {
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Enchanting extends $KubeRecipe {
public "costMultiplier"(costMultiplier: integer): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Enchanting$$Type = ($Enchanting);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Enchanting$$Original = $Enchanting;}
declare module "moe.wolfgirl.probejs.generated.schema.oritech.Pulverizer" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Pulverizer extends $KubeRecipe {
public "results"(results: $List$$Type<($ItemStack$$Type)>): this
public "ingredients"(ingredients: $List$$Type<($Ingredient$$Type)>): this
public "time"(time: integer): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Pulverizer$$Type = ($Pulverizer);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Pulverizer$$Original = $Pulverizer;}
declare module "moe.wolfgirl.probejs.generated.schema.extendedcrafting.ShapelessTable" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"
import {$CraftingBookCategory$$Type} from "net.minecraft.world.item.crafting.CraftingBookCategory"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $ShapelessTable extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "ingredients"(ingredients: $List$$Type<($Ingredient$$Type)>): this
public "category"(category: $CraftingBookCategory$$Type): this
public "buildingCategory"(): this
public "equipmentCategory"(): this
public "redstoneCategory"(): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ShapelessTable$$Type = ($ShapelessTable);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ShapelessTable$$Original = $ShapelessTable;}
declare module "moe.wolfgirl.probejs.generated.schema.minecraft.SmithingTransform" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $SmithingTransform extends $KubeRecipe {
public "result"(result: $ItemStack$$Type): this
public "template"(template: $Ingredient$$Type): this
public "base"(base: $Ingredient$$Type): this
public "addition"(addition: $Ingredient$$Type): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $SmithingTransform$$Type = ($SmithingTransform);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $SmithingTransform$$Original = $SmithingTransform;}
declare module "moe.wolfgirl.probejs.generated.registry.minecraft.ParticleType" {
import {$ParticleTypeBuilder} from "dev.latvian.mods.kubejs.misc.ParticleTypeBuilder"
import {$RegistryKubeEvent} from "dev.latvian.mods.kubejs.registry.RegistryKubeEvent"
import {$ParticleType as $ParticleType$0} from "net.minecraft.core.particles.ParticleType"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $ParticleType extends $RegistryKubeEvent<($ParticleType$0)> {
public "create"(name: StringJS): $ParticleTypeBuilder
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $ParticleType$$Type = ($ParticleType);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $ParticleType$$Original = $ParticleType;}
declare module "moe.wolfgirl.probejs.generated.schema.oritech.Laser" {
import {$ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$Ingredient$$Type} from "net.minecraft.world.item.crafting.Ingredient"
import {$KubeRecipe} from "dev.latvian.mods.kubejs.recipe.KubeRecipe"
import {$List$$Type} from "java.util.List"

/**
 * This is a class generated by ProbeJS, you shall not load/require this class for your usages
 * because it doesn't exist in the JVM. The class exist only for type hinting purpose.
 * Loading the class will not throw an error, but instead the class loaded will be undefined.
 */
export class $Laser extends $KubeRecipe {
public "results"(results: $List$$Type<($ItemStack$$Type)>): this
public "ingredients"(ingredients: $List$$Type<($Ingredient$$Type)>): this
public "time"(time: integer): this
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $Laser$$Type = ($Laser);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $Laser$$Original = $Laser;}
