declare module "xfacthd.framedblocks.api.blueprint.BlueprintData" {
import {$StreamCodec} from "net.minecraft.network.codec.StreamCodec"
import {$CamoList, $CamoList$$Type} from "xfacthd.framedblocks.api.util.CamoList"
import {$Optional, $Optional$$Type} from "java.util.Optional"
import {$Codec} from "com.mojang.serialization.Codec"
import {$RegistryFriendlyByteBuf} from "net.minecraft.network.RegistryFriendlyByteBuf"
import {$AuxBlueprintData, $AuxBlueprintData$$Type} from "xfacthd.framedblocks.api.blueprint.AuxBlueprintData"
import {$Block, $Block$$Type} from "net.minecraft.world.level.block.Block"
import {$BlockItemStateProperties, $BlockItemStateProperties$$Type} from "net.minecraft.world.item.component.BlockItemStateProperties"
import {$Record} from "java.lang.Record"

export class $BlueprintData extends $Record {
static readonly "CODEC": $Codec<($BlueprintData)>
static readonly "EMPTY": $BlueprintData
static readonly "STREAM_CODEC": $StreamCodec<($RegistryFriendlyByteBuf), ($BlueprintData)>

/**
 * 
 * @deprecated
 */
constructor(arg0: $Block$$Type, arg1: $CamoList$$Type, arg2: boolean, arg3: boolean, arg4: boolean, arg5: ($AuxBlueprintData$$Type<(never)>)?)
constructor(block: $Block$$Type, camos: $CamoList$$Type, glowing: boolean, intangible: boolean, reinforced: boolean, blockState: $BlockItemStateProperties$$Type, auxData: ($AuxBlueprintData$$Type<(never)>)?)

public "intangible"(): boolean
public "reinforced"(): boolean
public "glowing"(): boolean
public "camos"(): $CamoList
public "auxData"(): $Optional<($AuxBlueprintData<(never)>)>
public "withBlockState"(arg0: $BlockItemStateProperties$$Type): $BlueprintData
public "getAuxDataOrDefault"<T extends $AuxBlueprintData<(object)>>(arg0: T): T
public "withAuxData"(arg0: $AuxBlueprintData$$Type<(never)>): $BlueprintData
public "equals"(arg0: any): boolean
public "toString"(): StringJS
public "hashCode"(): integer
public "isEmpty"(): boolean
public "block"(): $Block
public "blockState"(): $BlockItemStateProperties
get "empty"(): boolean
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $BlueprintData$$Type = ({"glowing"?: boolean, "camos"?: $CamoList$$Type, "intangible"?: boolean, "auxData"?: ($AuxBlueprintData$$Type<(never)>)?, "blockState"?: $BlockItemStateProperties$$Type, "block"?: $Block$$Type, "reinforced"?: boolean}) | ([glowing?: boolean, camos?: $CamoList$$Type, intangible?: boolean, auxData?: ($AuxBlueprintData$$Type<(never)>)?, blockState?: $BlockItemStateProperties$$Type, block?: $Block$$Type, reinforced?: boolean]);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $BlueprintData$$Original = $BlueprintData;}
declare module "xfacthd.framedblocks.api.blueprint.AuxBlueprintData$Type" {
import {$StreamCodec, $StreamCodec$$Type} from "net.minecraft.network.codec.StreamCodec"
import {$RegistryFriendlyByteBuf, $RegistryFriendlyByteBuf$$Type} from "net.minecraft.network.RegistryFriendlyByteBuf"
import {$AuxBlueprintData} from "xfacthd.framedblocks.api.blueprint.AuxBlueprintData"
import {$MapCodec, $MapCodec$$Type} from "com.mojang.serialization.MapCodec"
import {$Record} from "java.lang.Record"

export class $AuxBlueprintData$Type<T extends $AuxBlueprintData<(object)>> extends $Record {
constructor(codec: $MapCodec$$Type<(T)>, streamCodec: $StreamCodec$$Type<($RegistryFriendlyByteBuf$$Type), (T)>)

public "streamCodec"(): $StreamCodec<($RegistryFriendlyByteBuf), (T)>
public "equals"(arg0: any): boolean
public "toString"(): StringJS
public "hashCode"(): integer
public "codec"(): $MapCodec<(T)>
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Literal": Special.FramedblocksAuxBlueprintData
/**
 * This field is a type stub generated by ProbeJS and shall not be used in any sense.
 */
 "probejsInternal$$Tag": Special.FramedblocksAuxBlueprintDataTag
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $AuxBlueprintData$Type$$Type<T> = (Special.FramedblocksAuxBlueprintData) | ({"streamCodec"?: $StreamCodec$$Type<($RegistryFriendlyByteBuf$$Type), (T)>, "codec"?: $MapCodec$$Type<(T)>}) | ([streamCodec?: $StreamCodec$$Type<($RegistryFriendlyByteBuf$$Type), (T)>, codec?: $MapCodec$$Type<(T)>]);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $AuxBlueprintData$Type$$Original<T> = $AuxBlueprintData$Type<(T)>;}
declare module "xfacthd.framedblocks.api.blueprint.AuxBlueprintData" {
import {$StreamCodec} from "net.minecraft.network.codec.StreamCodec"
import {$Registry} from "net.minecraft.core.Registry"
import {$AuxBlueprintData$Type} from "xfacthd.framedblocks.api.blueprint.AuxBlueprintData$Type"
import {$Codec} from "com.mojang.serialization.Codec"
import {$RegistryFriendlyByteBuf} from "net.minecraft.network.RegistryFriendlyByteBuf"

export interface $AuxBlueprintData$$Interface<T extends $AuxBlueprintData<(object)>> {
}

export class $AuxBlueprintData<T extends $AuxBlueprintData<(object)>> implements $AuxBlueprintData$$Interface {
static readonly "CODEC": $Codec<($AuxBlueprintData<(never)>)>
static readonly "STREAM_CODEC": $StreamCodec<($RegistryFriendlyByteBuf), ($AuxBlueprintData<(never)>)>
static readonly "REGISTRY": $Registry<($AuxBlueprintData$Type<(never)>)>

 "type"(): $AuxBlueprintData$Type<(T)>
 "equals"(arg0: any): boolean
 "hashCode"(): integer
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $AuxBlueprintData$$Type<T> = ($AuxBlueprintData<(T)>);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $AuxBlueprintData$$Original<T> = $AuxBlueprintData<(T)>;}
declare module "xfacthd.framedblocks.api.blueprint.BlueprintCopyBehaviour" {
import {$Player$$Type} from "net.minecraft.world.entity.player.Player"
import {$CamoList} from "xfacthd.framedblocks.api.util.CamoList"
import {$ItemStack, $ItemStack$$Type} from "net.minecraft.world.item.ItemStack"
import {$List} from "java.util.List"
import {$Level$$Type} from "net.minecraft.world.level.Level"
import {$FramedBlockEntity$$Type} from "xfacthd.framedblocks.api.block.blockentity.FramedBlockEntity"
import {$BlueprintData, $BlueprintData$$Type} from "xfacthd.framedblocks.api.blueprint.BlueprintData"
import {$BlockPos$$Type} from "net.minecraft.core.BlockPos"
import {$Property} from "net.minecraft.world.level.block.state.properties.Property"
import {$BlockState$$Type} from "net.minecraft.world.level.block.state.BlockState"

export interface $BlueprintCopyBehaviour$$Interface {
}

export class $BlueprintCopyBehaviour implements $BlueprintCopyBehaviour$$Interface {
 "writeToBlueprint"(arg0: $Level$$Type, arg1: $BlockPos$$Type, arg2: $BlockState$$Type, arg3: $FramedBlockEntity$$Type): $BlueprintData
 "getAdditionalConsumedMaterials"(arg0: $BlueprintData$$Type): $List<($ItemStack)>
 "getPropertiesToCopy"(arg0: $BlockState$$Type): $List<($Property<(never)>)>
 "postProcessPaste"(arg0: $Level$$Type, arg1: $BlockPos$$Type, arg2: $Player$$Type, arg3: $BlueprintData$$Type, arg4: $ItemStack$$Type): void
 "getGlowstoneCount"(arg0: $BlueprintData$$Type): integer
 "getIntangibleCount"(arg0: $BlueprintData$$Type): integer
 "getReinforcementCount"(arg0: $BlueprintData$$Type): integer
 "getCamos"(arg0: $BlueprintData$$Type): $CamoList
 "attachDataToDummyRenderStack"(arg0: $ItemStack$$Type, arg1: $BlueprintData$$Type): void
 "getBlockItem"(arg0: $BlueprintData$$Type): $ItemStack
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $BlueprintCopyBehaviour$$Type = ($BlueprintCopyBehaviour);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $BlueprintCopyBehaviour$$Original = $BlueprintCopyBehaviour;}
declare module "xfacthd.framedblocks.api.blueprint.RegisterBlueprintCopyBehavioursEvent" {
import {$BlueprintCopyBehaviour$$Type} from "xfacthd.framedblocks.api.blueprint.BlueprintCopyBehaviour"
import {$List$$Type} from "java.util.List"
import {$BiConsumer$$Type} from "java.util.function.BiConsumer"
import {$Block$$Type} from "net.minecraft.world.level.block.Block"
import {$Event} from "net.neoforged.bus.api.Event"
import {$IModBusEvent$$Interface} from "net.neoforged.fml.event.IModBusEvent"
import {$Holder$$Type} from "net.minecraft.core.Holder"

export class $RegisterBlueprintCopyBehavioursEvent extends $Event implements $IModBusEvent$$Interface {
constructor(arg0: $BiConsumer$$Type<($BlueprintCopyBehaviour), (($Block)[])>)

public "register"(arg0: $BlueprintCopyBehaviour$$Type, ...arg1: ($Block$$Type)[]): void
public "register"(arg0: $BlueprintCopyBehaviour$$Type, arg1: $List$$Type<($Holder$$Type<($Block$$Type)>)>): void
public "register"(arg0: $BlueprintCopyBehaviour$$Type, arg1: $Holder$$Type<($Block)>): void
}
/**
 * Class-specific type exported by ProbeJS, use global Type_
 * types for convenience unless there's a naming conflict.
 */
export type $RegisterBlueprintCopyBehavioursEvent$$Type = ($RegisterBlueprintCopyBehavioursEvent);
/**
 * Original type to represent the class type itself. Use in JSDoc only.
 */
export type $RegisterBlueprintCopyBehavioursEvent$$Original = $RegisterBlueprintCopyBehavioursEvent;}
